version: '3.3'

services:
    places_api:
      build: .
      ports:
      - "8080:8080"
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/places
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=secret
      depends_on:
      - postgres
      volumes:
        - maven_repo:/root/.m2/repository
    postgres:
      image: postgis/postgis:13-3.3-alpine
      ports:
      - "5432:5432"
      environment:
        POSTGRES_PASSWORD: secret
      volumes:
        - postgres_storage:/var/lib/postgresql/data
        - ./docker/places_db:/docker-entrypoint-initdb.d

volumes:
  postgres_storage: {}
  maven_repo: {}
